export const PAIRS = [
  { pair: "BTCUSDT", symbol: "BTC", name: "Bitcoin" },
  { pair: "ETHUSDT", symbol: "ETH", name: "Ethereum" },
  { pair: "BNBUSDT", symbol: "BNB", name: "BNB" },
  { pair: "SOLUSDT", symbol: "SOL", name: "Solana" },
  { pair: "ARBUSDT", symbol: "ARB", name: "Arbitrum" },
  { pair: "XRPUSDT", symbol: "XRP", name: "XRP" },
  { pair: "DOGEUSDT", symbol: "DOGE", name: "Dogecoin" },
  { pair: "ADAUSDT", symbol: "ADA", name: "Cardano" },
  { pair: "AVAXUSDT", symbol: "AVAX", name: "Avalanche" },
  { pair: "DOTUSDT", symbol: "DOT", name: "Polkadot" },
  { pair: "LINKUSDT", symbol: "LINK", name: "Chainlink" },
  { pair: "LTCUSDT", symbol: "LTC", name: "Litecoin" },
  { pair: "UNIUSDT", symbol: "UNI", name: "Uniswap" },
  { pair: "ATOMUSDT", symbol: "ATOM", name: "Cosmos" },
  { pair: "TRXUSDT", symbol: "TRX", name: "TRON" },
  { pair: "XLMUSDT", symbol: "XLM", name: "Stellar" },
  { pair: "NEARUSDT", symbol: "NEAR", name: "NEAR Protocol" },
  { pair: "ALGOUSDT", symbol: "ALGO", name: "Algorand" },
  { pair: "ETCUSDT", symbol: "ETC", name: "Ethereum Classic" },
  { pair: "MATICUSDT", symbol: "MATIC", name: "Polygon" },
];

export const COIN_ICONS = {
  BTC: "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png",
  ETH: "https://coin-images.coingecko.com/coins/images/279/large/ethereum.png",
  BNB: "https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png",
  SOL: "https://coin-images.coingecko.com/coins/images/4128/large/solana.png",
  XRP: "https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png",
  ARB: "https://assets.coingecko.com/coins/images/16547/standard/arb.jpg?1721358242",
  DOGE: "https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png",
  ADA: "https://coin-images.coingecko.com/coins/images/975/large/cardano.png",
  AVAX: "https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png",
  DOT: "https://coin-images.coingecko.com/coins/images/12171/large/polkadot.png",
  LINK: "https://coin-images.coingecko.com/coins/images/877/large/chainlink-new-logo.png",
  LTC: "https://coin-images.coingecko.com/coins/images/2/large/litecoin.png",
  UNI: "https://coin-images.coingecko.com/coins/images/12504/large/uniswap-uni.png",
  ATOM: "https://coin-images.coingecko.com/coins/images/1481/large/cosmos_hub.png",
  TRX: "https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png",
  XLM: "https://coin-images.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png",
  NEAR: "https://coin-images.coingecko.com/coins/images/10365/large/near.jpg",
  ALGO: "https://assets.coingecko.com/coins/images/4380/standard/download.png?1696504978",
  ETC: "https://coin-images.coingecko.com/coins/images/453/large/ethereum-classic-logo.png",
  MATIC: "https://coin-images.coingecko.com/coins/images/4713/large/matic-token-icon.png",
};
