export const packages = [
  {
    id: "starter",
    name: "Starter Package",
    amount: 10,
    totalReturn: 20,
    dailyPayment: 0.05479452,
    durationDays: 365,
    captchaRequiredPerDay: 12,
    captchaTaskDurationSeconds: 30,
  },
  {
    id: "growth",
    name: "Growth Package",
    amount: 25,
    totalReturn: 50,
    dailyPayment: 0.13698630,
    durationDays: 365,
    captchaRequiredPerDay: 20,
    captchaTaskDurationSeconds: 30,
  },
  {
    id: "advanced",
    name: "Advanced Package",
    amount: 50,
    totalReturn: 100,
    dailyPayment: 0.27397260,
    durationDays: 365,
    captchaRequiredPerDay: 25,
    captchaTaskDurationSeconds: 30,
  },
  {
    id: "pro",
    name: "Pro Package",
    amount: 100,
    totalReturn: 200,
    dailyPayment: 0.54794521,
    durationDays: 365,
    captchaRequiredPerDay: 30,
    captchaTaskDurationSeconds: 30,
  },
  {
    id: "elite",
    name: "Elite Package",
    amount: 500,
    totalReturn: 1000,
    dailyPayment: 2.73972603,
    durationDays: 365,
    captchaRequiredPerDay: 40,
    captchaTaskDurationSeconds: 30,
  },
  {
    id: "vip",
    name: "VIP Package",
    amount: 1000,
    totalReturn: 2000,
    dailyPayment: 5.47945205,
    durationDays: 365,
    captchaRequiredPerDay: 60,
    captchaTaskDurationSeconds: 30,
  },
];
