"""add wallet system to users

Revision ID: 04da24f314a0
Revises: 224c5f2cb4be
Create Date: 2026-02-19 01:07:01.557116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04da24f314a0'
down_revision: Union[str, Sequence[str], None] = '224c5f2cb4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main_wallet', sa.Numeric(precision=24, scale=14), server_default='0', nullable=True))
    op.add_column('users', sa.Column('deposit_wallet', sa.Numeric(precision=24, scale=14), server_default='0', nullable=True))
    op.add_column('users', sa.Column('withdraw_wallet', sa.Numeric(precision=24, scale=14), server_default='0', nullable=True))
    op.add_column('users', sa.Column('referral_wallet', sa.Numeric(precision=24, scale=14), server_default='0', nullable=True))
    op.add_column('users', sa.Column('generation_wallet', sa.Numeric(precision=24, scale=14), server_default='0', nullable=True))
    op.add_column('users', sa.Column('arbx_wallet', sa.Numeric(precision=24, scale=14), server_default='100', nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('users', 'arbx_wallet')
    op.drop_column('users', 'generation_wallet')
    op.drop_column('users', 'referral_wallet')
    op.drop_column('users', 'withdraw_wallet')
    op.drop_column('users', 'deposit_wallet')
    op.drop_column('users', 'main_wallet')
    # ### end Alembic commands ###
