"""added otp fields

Revision ID: 1623bca09faa
Revises: 9c3b522553f2
Create Date: 2026-02-13 17:23:31.037604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1623bca09faa'
down_revision: Union[str, Sequence[str], None] = '9c3b522553f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    op.drop_column('users', 'parent_lvl_5_id')
    op.drop_column('users', 'parent_lvl_4_id')
    op.drop_column('users', 'parent_lvl_2_id')
    op.drop_column('users', 'parent_lvl_3_id')
    op.drop_column('users', 'parent_lvl_1_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_lvl_1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('parent_lvl_3_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('parent_lvl_2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('parent_lvl_4_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('parent_lvl_5_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###
