"""add full_name to users

Revision ID: 224c5f2cb4be
Revises: 6d882a3f55ac
Create Date: 2026-02-19 00:50:55.312703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224c5f2cb4be'
down_revision: Union[str, Sequence[str], None] = '6d882a3f55ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'full_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_full_name'), 'users',
                    ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
