"""add email_verified field

Revision ID: 2c55aa8d340b
Revises: 64d0b5b045d5
Create Date: 2026-02-15 00:53:51.736284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c55aa8d340b'
down_revision: Union[str, Sequence[str], None] = '64d0b5b045d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column with server default
    op.add_column(
        'users',
        sa.Column(
            'email_verified',
            sa.Boolean(),
            nullable=True,
            server_default=sa.text('false')
        )
    )

    # Step 2: Ensure existing rows are false
    op.execute("UPDATE users SET email_verified = FALSE")

    # Step 3: Make NOT NULL (keep default)
    op.alter_column(
        'users',
        'email_verified',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
