"""add referral and admin fields

Revision ID: 3554e486ef00
Revises: f6718131f331
Create Date: 2026-02-02 00:44:53.940607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3554e486ef00'
down_revision: Union[str, Sequence[str], None] = 'f6718131f331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code',
                  sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column(
        'referred_by', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_referral_code'),
                    'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'referral_code')
    # ### end Alembic commands ###
