"""create platform stats table

Revision ID: 53da0533bbb2
Revises: f2a1c9e6d5b7
Create Date: 2026-03-07 19:54:43.934364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53da0533bbb2'
down_revision: Union[str, Sequence[str], None] = 'f2a1c9e6d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=24, scale=14), nullable=False),
    sa.Column('total_withdrawn', sa.Numeric(precision=24, scale=14), nullable=False),
    sa.Column('total_profit_shared', sa.Numeric(precision=24, scale=14), nullable=False),
    sa.Column('active_investors', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_stats')
    # ### end Alembic commands ###
