"""add kyc table

Revision ID: 553fb8f02c67
Revises: 03e9daf6136c
Create Date: 2026-02-16 19:28:06.927567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553fb8f02c67'
down_revision: Union[str, Sequence[str], None] = '03e9daf6136c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.Enum('nid', 'passport', name='documenttype'), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('front_image_key', sa.String(length=255), nullable=False),
    sa.Column('back_image_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='kycstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_kyc_verifications_id'), 'kyc_verifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_verifications_id'), table_name='kyc_verifications')
    op.drop_table('kyc_verifications')
    # ### end Alembic commands ###
