"""removed otp fields

Revision ID: 64d0b5b045d5
Revises: 70bc11404ed9
Create Date: 2026-02-13 17:55:26.290915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64d0b5b045d5'
down_revision: Union[str, Sequence[str], None] = '70bc11404ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'otp_expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
