"""remove nid_passport from users

Revision ID: 6d882a3f55ac
Revises: 553fb8f02c67
Create Date: 2026-02-16 19:47:12.594126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d882a3f55ac'
down_revision: Union[str, Sequence[str], None] = '553fb8f02c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nid_passport'), table_name='users')
    op.drop_column('users', 'nid_passport')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nid_passport', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_nid_passport'), 'users', ['nid_passport'], unique=True)
    # ### end Alembic commands ###
