"""fix level fields

Revision ID: 70bc11404ed9
Revises: 1623bca09faa
Create Date: 2026-02-13 17:34:15.690514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bc11404ed9'
down_revision: Union[str, Sequence[str], None] = '1623bca09faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_lvl_1_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parent_lvl_2_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parent_lvl_3_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parent_lvl_4_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parent_lvl_5_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parent_lvl_5_id')
    op.drop_column('users', 'parent_lvl_4_id')
    op.drop_column('users', 'parent_lvl_3_id')
    op.drop_column('users', 'parent_lvl_2_id')
    op.drop_column('users', 'parent_lvl_1_id')
    # ### end Alembic commands ###
