"""remove referred_by from users

Revision ID: 74a07f056463
Revises: 49105d22df16
Create Date: 2026-02-05 01:19:18.321623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a07f056463'
down_revision: Union[str, Sequence[str], None] = '49105d22df16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referred_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
