"""add phone number to kyc

Revision ID: 7e3dc958ffe6
Revises: 36bfc88ccb5c
Create Date: 2026-02-19 05:30:57.899123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3dc958ffe6'
down_revision: Union[str, Sequence[str], None] = '36bfc88ccb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_verifications', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('kyc_verifications', 'phone_number')
    # ### end Alembic commands ###
