"""add investment system

Revision ID: a74e0a1d14bd
Revises: d0e9bd332692
Create Date: 2026-03-05 04:08:29.429764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74e0a1d14bd'
down_revision: Union[str, Sequence[str], None] = 'd0e9bd332692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=24, scale=14), nullable=False),
    sa.Column('roi_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('expected_profit', sa.Numeric(precision=24, scale=14), nullable=False),
    sa.Column('profit_earned', sa.Numeric(precision=24, scale=14), server_default='0', nullable=False),
    sa.Column('profit_percentage_paid', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_user_id'), 'investments', ['user_id'], unique=False)
    op.create_table('investment_profit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=14), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_profit_history_investment_id'), 'investment_profit_history', ['investment_id'], unique=False)
    op.create_table('referral_profit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=14), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_profit_history')
    op.drop_index(op.f('ix_investment_profit_history_investment_id'), table_name='investment_profit_history')
    op.drop_table('investment_profit_history')
    op.drop_index(op.f('ix_investments_user_id'), table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###
