"""add arbx mining wallet

Revision ID: c60bc0fd855c
Revises: 7e3dc958ffe6
Create Date: 2026-03-01 02:18:46.466320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60bc0fd855c'
down_revision: Union[str, Sequence[str], None] = '7e3dc958ffe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('arbx_mining_wallet', sa.Numeric(precision=24, scale=14), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'arbx_mining_wallet')
    # ### end Alembic commands ###
