"""update user wallet fields

Revision ID: d0e9bd332692
Revises: 831df65eb2ec
Create Date: 2026-03-05 01:17:05.547354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e9bd332692'
down_revision: Union[str, Sequence[str], None] = '831df65eb2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mining_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_mining', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_mining')
    op.drop_column('users', 'mining_started_at')
    # ### end Alembic commands ###
