"""add user ancestry columns

Revision ID: d2d5b3ea5332
Revises: 3554e486ef00
Create Date: 2026-02-05 00:41:32.425639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d5b3ea5332'
down_revision: Union[str, Sequence[str], None] = '3554e486ef00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_lvl_1_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parent_lvl_2_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parent_lvl_3_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parent_lvl_4_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parent_lvl_5_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_column('users', 'parent_lvl_5_id')
    op.drop_column('users', 'parent_lvl_4_id')
    op.drop_column('users', 'parent_lvl_3_id')
    op.drop_column('users', 'parent_lvl_2_id')
    op.drop_column('users', 'parent_lvl_1_id')
    # ### end Alembic commands ###
