export const countries = [
  { name: "United States", code: "US", flag: "🇺🇸" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧" },
  { name: "Canada", code: "CA", flag: "🇨🇦" },
  { name: "Australia", code: "AU", flag: "🇦🇺" },
  { name: "Germany", code: "DE", flag: "🇩🇪" },
  { name: "France", code: "FR", flag: "🇫🇷" },
  { name: "Japan", code: "JP", flag: "🇯🇵" },
  { name: "South Korea", code: "KR", flag: "🇰🇷" },
  { name: "India", code: "IN", flag: "🇮🇳" },
  { name: "Brazil", code: "BR", flag: "🇧🇷" },
  { name: "Mexico", code: "MX", flag: "🇲🇽" },
  { name: "Italy", code: "IT", flag: "🇮🇹" },
  { name: "Spain", code: "ES", flag: "🇪🇸" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱" },
  { name: "Sweden", code: "SE", flag: "🇸🇪" },
  { name: "Norway", code: "NO", flag: "🇳🇴" },
  { name: "Denmark", code: "DK", flag: "🇩🇰" },
  { name: "Finland", code: "FI", flag: "🇫🇮" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭" },
  { name: "Austria", code: "AT", flag: "🇦🇹" },
  { name: "Belgium", code: "BE", flag: "🇧🇪" },
  { name: "Portugal", code: "PT", flag: "🇵🇹" },
  { name: "Ireland", code: "IE", flag: "🇮🇪" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿" },
  { name: "Singapore", code: "SG", flag: "🇸🇬" },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰" },
  { name: "UAE", code: "AE", flag: "🇦🇪" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦" },
  { name: "Qatar", code: "QA", flag: "🇶🇦" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭" },
  { name: "Oman", code: "OM", flag: "🇴🇲" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬" },
  { name: "Kenya", code: "KE", flag: "🇰🇪" },
  { name: "Egypt", code: "EG", flag: "🇪🇬" },
  { name: "Morocco", code: "MA", flag: "🇲🇦" },
  { name: "Ghana", code: "GH", flag: "🇬🇭" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹" },
  { name: "Uganda", code: "UG", flag: "🇺🇬" },
  { name: "Israel", code: "IL", flag: "🇮🇱" },
  { name: "Turkey", code: "TR", flag: "🇹🇷" },
  { name: "Russia", code: "RU", flag: "🇷🇺" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦" },
  { name: "Poland", code: "PL", flag: "🇵🇱" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿" },
  { name: "Romania", code: "RO", flag: "🇷🇴" },
  { name: "Hungary", code: "HU", flag: "🇭🇺" },
  { name: "Greece", code: "GR", flag: "🇬🇷" },
  { name: "Croatia", code: "HR", flag: "🇭🇷" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬" },
  { name: "Serbia", code: "RS", flag: "🇷🇸" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹" },
  { name: "Latvia", code: "LV", flag: "🇱🇻" },
  { name: "Estonia", code: "EE", flag: "🇪🇪" },
  { name: "Iceland", code: "IS", flag: "🇮🇸" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺" },
  { name: "Malta", code: "MT", flag: "🇲🇹" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾" },
  { name: "Thailand", code: "TH", flag: "🇹🇭" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳" },
  { name: "Philippines", code: "PH", flag: "🇵🇭" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼" },
  { name: "China", code: "CN", flag: "🇨🇳" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰" },
  { name: "Nepal", code: "NP", flag: "🇳🇵" },
  { name: "Argentina", code: "AR", flag: "🇦🇷" },
  { name: "Chile", code: "CL", flag: "🇨🇱" },
  { name: "Colombia", code: "CO", flag: "🇨🇴" },
  { name: "Peru", code: "PE", flag: "🇵🇪" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾" },
  { name: "Bolivia", code: "BO", flag: "🇧🇴" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷" },
  { name: "Panama", code: "PA", flag: "🇵🇦" },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴" },
  { name: "Jamaica", code: "JM", flag: "🇯🇲" },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹" },
  { name: "Barbados", code: "BB", flag: "🇧🇧" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸" },
  { name: "Haiti", code: "HT", flag: "🇭🇹" },
  { name: "Cuba", code: "CU", flag: "🇨🇺" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹" },
  { name: "Honduras", code: "HN", flag: "🇭🇳" },
  { name: "El Salvador", code: "SV", flag: "🇸🇻" },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭" },
  { name: "Myanmar", code: "MM", flag: "🇲🇲" },
  { name: "Laos", code: "LA", flag: "🇱🇦" },
  { name: "Mongolia", code: "MN", flag: "🇲🇳" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿" },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿" },
  { name: "Georgia", code: "GE", flag: "🇬🇪" },
  { name: "Armenia", code: "AM", flag: "🇦🇲" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧" },
  { name: "Jordan", code: "JO", flag: "🇯🇴" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶" },
  { name: "Iran", code: "IR", flag: "🇮🇷" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳" },
  { name: "Libya", code: "LY", flag: "🇱🇾" },
  { name: "Sudan", code: "SD", flag: "🇸🇩" },
  { name: "Senegal", code: "SN", flag: "🇸🇳" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲" },
  { name: "Ivory Coast", code: "CI", flag: "🇨🇮" },
  { name: "Democratic Republic of the Congo", code: "CD", flag: "🇨🇩" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲" },
  { name: "Botswana", code: "BW", flag: "🇧🇼" },
  { name: "Namibia", code: "NA", flag: "🇳🇦" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬" },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿" },
  { name: "Angola", code: "AO", flag: "🇦🇴" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼" },
  { name: "Burundi", code: "BI", flag: "🇧🇮" },
  { name: "Malawi", code: "MW", flag: "🇲🇼" },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬" },
  { name: "Fiji", code: "FJ", flag: "🇫🇯" },
  { name: "Solomon Islands", code: "SB", flag: "🇸🇧" },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺" },
  { name: "Samoa", code: "WS", flag: "🇼🇸" },
  { name: "Tonga", code: "TO", flag: "🇹🇴" },
  { name: "Panama", code: "PA", flag: "🇵🇦" },
];
